spring:
  application:
    name: service-zuul
server:
  port: 8768
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-hi1
    api-b:
      path: /api-b/**
      serviceId: service-hi2
