#eureka:
#  instance:
#    hostname: 127.0.0.1
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#    eureka-server-u-r-l-context: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-server
---
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  profiles: peer1

---
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
spring:
  profiles: peer2

---
server:
  port: 8763
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
spring:
  profiles:
    active: peer3