spring:
  application:
    name: service-hi
server:
  servlet:
    context-path: /hi-client
---
server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  profiles: hi1
---
server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  profiles: hi2